services:
  db:
    image: mysql
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: root_pwd
      MYSQL_DATABASE: api
      MYSQL_USER: new_user
      MYSQL_PASSWORD: my_pwd
    ports:
      - "3306:3306"

      
  api:
    build: .
    depends_on:
      - db
    ports:
      - 9000:9000
    environment:
      - DB_SERVER=db
      - DB_PORT=3306
      - DB_DATABASE=api
      - DB_USER=root
      - DB_PASSWORD=root_pwd

    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network: