name: Continuous Integration

on: 
    push

jobs: 
    build_and_push:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout
            uses: actions/checkout@v5
          - name: Login to Docker Hub
            uses: docker/login-action@v3
            with:
                username: ${{ vars.DOCKER_USER }}
                password: ${{ secrets.DOCKER_TOKEN }}
          - name: Set up Docker Build
            uses: docker/setup-buildx-action@v3
            with:
              push: true
              tags: samuelfialho1/study-apir:latest